### ISSUE TITLE
 When will the version upgrade date be?

### ISSUE THREAD

**Issue by dc7303** [tylernhoward/ngx-tui-editor#10]
Previously I requested a pull request for the viewer and Tui-Editor namespace error issues. Thank you for your reflection.
When will the npm version be upgraded?

**Comment by DamjanHatrix** [comment]
Bumb.

**Comment by tylernhoward** [comment]
Sorry for the delay! Life happens sometimes! Updated last night and tested to be working under 0.3.4. There is an issue with the image toolbar that will be addressed in a subsequent issue

**Comment by tylernhoward** [comment]
@dc7303 Thank you for your patience! Let me know if you have any problems with the latest ngx-tui-editor (0.3.4)
