### ISSUE TITLE
Does not work with Angular 6 

### ISSUE THREAD

**Issue by kaangoksal** [tylernhoward/ngx-tui-editor#4]
I couldn't get it working with Angular 6, getting the following error:
`
ERROR Error: "Uncaught (in promise): Error: Template parse errors:
'tui-editor' is not a known element:
1. If 'tui-editor' is an Angular component, then verify that it is part of this module.
2. If 'tui-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
  help-center-create-document works!
</p>`

**Comment by tylernhoward** [comment]
Thanks for bringing this up! I will take a look when I get a moment

**Comment by tylernhoward** [comment]
Closed with #9
