### ISSUE TITLE
Question : Possible to disable the preview styling ?

### ISSUE THREAD

**Issue by j-kwan** [tylernhoward/ngx-tui-editor#6]
Hi,
Is it possible to disable the style in the preview mode ?
I would like to keep the style of my application for having the real final rendering.

**Comment by tylernhoward** [comment]
I'm not sure, is this a possibility in https://github.com/nhnent/tui.editor?

**Comment by tylernhoward** [comment]
This is not currently a feature of https://github.com/nhnent/tui.editor. Reopen or submit a PR if i am incorrect :)
