### ISSUE TITLE
Cannot use namespace 'TuiEditor' as a type.

### ISSUE THREAD

**Issue by mateotherock** [tylernhoward/ngx-tui-editor#7]
First off, this package works terrific. I'm using it on Ionic 3/Angular 6 application. The only thing that I get is an error on serve/build/deploy of my application 'Cannot use namespace 'TuiEditor' as a type'. This is on line 7 of tui-editor.component.d.ts file where editor is declared as type TuiEditor. I'm not sure why I am getting this error. If I change to type 'any' it works just fine of course, but I'd rather have a long term fix for this if possible.

**Comment by mateotherock** [comment]
Actually I think we can just add .default to that type and it should satisfy. I just created a pull request if that is okay. Thanks again for this package!

**Comment by tylernhoward** [comment]
Let's set this to `any` for the time being and we can revisit later. This work is done in PR #9 :) Thanks for the contribution!
